### ISSUE TITLE
Attribute data size value out of bounds

### ISSUE THREAD

**Issue by icewideshut** [libyal/libfsntfs#21] opened 2020-10-27 11:46 UTC
I've been built fsntfsinfo project for Win32 platform.
Then executed fsntfsinfo.exe on Windows x64 Build 1909 with command line (-E all -v \\.\C: > test.txt) to enumerate all mft entries.
But it showed errors on some of the entries as shown below. 

![libfsntfscmd](https://user-images.githubusercontent.com/73529823/97297238-c96a9880-1862-11eb-862e-963623dcce94.png)

When I tried to another library like [ntfstool](https://github.com/thewhiteninja/ntfstool) it shows all entries without any error. 
Because of this I tried to trace libfsntfs code pieces and found that libfsntfs checking size for any possible overflow.

![libfsntfsfunc](https://user-images.githubusercontent.com/73529823/97297308-e56e3a00-1862-11eb-90ae-aaabd1d11fd1.png)

But I thinking that checking is actually not true for the 64-bit operating system case. Because SSIZE_MAX defined for just 32bit architecture. It may dynamically change to 64 bit checking in 64 bit OS. 

![libfsntfsheader](https://user-images.githubusercontent.com/73529823/97297329-ee5f0b80-1862-11eb-831d-9d4e1a1ccf6d.png)

Also when I looking for references for SSIZE_MAX, saw that used in many areas.
![libfsntfsrefer](https://user-images.githubusercontent.com/73529823/97297350-f454ec80-1862-11eb-919e-4e35599c1c46.png)

**Comment by joachimmetz** [comment] 2020-10-27 11:57
> It may dynamically change to 64 bit checking in 64 bit OS.

Not sure what you mean with "dynamically change" here, these are compiler pre-processor macros. That means either `INT32_MAX` or `INT64_MAX` will be compiled in.

If `SSIZE_MAX` is `INT32_MAX` or `INT64_MAX` does not change the fact that the size value is unusually large. This check is mainly intended to detect sign changes. Which should not happen since https://github.com/libyal/libfsntfs/blob/master/common/memory.h#L45

Can you provide me with the details of the input data. See: https://github.com/libyal/libfsntfs/wiki/Troubleshooting#verbose-and-debug-output

**Comment by icewideshut** [comment] 2020-10-27 13:32
First of all, I'm actually wondering why it's not checking for INT64_MAX instead of SSIZE_MAX.Because mft_attribute->data_size already uint64 type ?

I enabled only the verbose output. Because when enabled debug output seems not to finished processing. The result is a bit the same.

![libfsntfs5931err](https://user-images.githubusercontent.com/73529823/97308221-b0b5af00-1871-11eb-94d4-c7886f286b41.png)

To provide more details I ll go on entry 5931 which one of the same errors. 

First of all the below is the output of ntfstool output.

[ntfstools.txt](https://github.com/libyal/libfsntfs/files/5445532/ntfstools.txt)

File information.

![2016vmdk](https://user-images.githubusercontent.com/73529823/97308111-8b28a580-1871-11eb-8136-637b86e3a79b.png)

And finally tried to do comment code blocks which are checking for size. And try again the process entry 5931 with fsntfsinfo. Below is the result.

[libfsntfs.txt](https://github.com/libyal/libfsntfs/files/5445577/libfsntfs.txt)

**Comment by joachimmetz** [comment] 2020-10-27 14:12
> First of all, I'm actually wondering why it's not checking for INT64_MAX instead of SSIZE_MAX.Because
> mft_attribute->data_size already uint64 type ?

Because data_size is `size_t` https://github.com/libyal/libfsntfs/blob/e5a015c12c6f71434fccbf5f3a1c18249d0d380f/libfsntfs/libfsntfs_mft_attribute.c#L1838 

And by the error message it is trying to get the data of a resident attribute which should not exceed the MFT entry size.

https://github.com/libyal/libfsntfs/blob/e5a015c12c6f71434fccbf5f3a1c18249d0d380f/libfsntfs/libfsntfs_file_entry.c#L295
https://github.com/libyal/libfsntfs/blob/e5a015c12c6f71434fccbf5f3a1c18249d0d380f/libfsntfs/libfsntfs_cluster_block_stream.c#L827

So libfsntfs is trying to set up a data stream for one of the `$DATA` attributes. I suspect the one that is 2667970560 bytes. I don't see any mention of `$DATA` attributes in the ntfstools output.

The debug output could help to see what data the `$DATA` MFT  attribute actually sets the resident flag.

**Comment by icewideshut** [comment] 2020-10-27 14:52
Okay, I could get it. Both debug and verbose output attached.

[libfsntfsinfo.txt](https://github.com/libyal/libfsntfs/files/5446097/libfsntfsinfo.txt)

**Comment by joachimmetz** [comment] 2020-10-27 18:21
thx, for the debug data. I think I see what the issue is. It is treating a non-resident attribute as a resident one and should basically ignore the size check for the non-resident case and set data to NULL. I'll make some changes to account for this situation.

**Comment by joachimmetz** [comment] 2020-10-27 19:25
Some changes in https://github.com/libyal/libfsntfs/commit/ee9c60a71a6d3ebcd0b85f07281b820c2407d647

**Comment by icewideshut** [comment] 2020-10-28 10:31
> Some changes in [ee9c60a](https://github.com/libyal/libfsntfs/commit/ee9c60a71a6d3ebcd0b85f07281b820c2407d647)

After the changes, it worked like a charm :)

`fsntfsinfo 20200921

MFT entry: 5931 information:
        Is allocated                    : true
        File reference                  : 5931-136
        Base record file reference      : Not set (0)
        Journal sequence number         : 213308514650
        Number of attributes            : 7

Attribute: 1
        Type                            : $STANDARD_INFORMATION (0x00000010)
        Creation time                   : Sep 07, 2020 15:45:04.490507400 UTC
        Modification time               : Sep 07, 2020 15:57:45.544745300 UTC
        Access time                     : Sep 07, 2020 15:57:45.544745300 UTC
        Entry modification time         : Sep 07, 2020 15:57:45.544745300 UTC
        Owner identifier                : 0
        Security descriptor identifier  : 1716
        Update sequence number          : 33356310032
        File attribute flags            : 0x00000020
                Should be archived (FILE_ATTRIBUTE_ARCHIVE)

Attribute: 2
        Type                            : $ATTRIBUTE_LIST (0x00000020)
        Data size                       : 192 bytes
        Number of entries               : 6
        Entry: 0                        : $STANDARD_INFORMATION (0x00000010) in file reference: 5931-136
        Entry: 1                        : $FILE_NAME (0x00000030) in file reference: 5931-136
        Entry: 2                        : $FILE_NAME (0x00000030) in file reference: 5931-136
        Entry: 3                        : $DATA (0x00000080) in file reference: 1317373-16
        Entry: 4                        : $DATA (0x00000080) in file reference: 27206-222
        Entry: 5                        : $DATA (0x00000080) in file reference: 1915487-17

Attribute: 3
        Type                            : $FILE_NAME (0x00000030)
        Parent file reference           : 707654-48
        Creation time                   : Sep 07, 2020 15:45:04.490507400 UTC
        Modification time               : Sep 07, 2020 15:45:04.490507400 UTC
        Access time                     : Sep 07, 2020 15:45:04.490507400 UTC
        Entry modification time         : Sep 07, 2020 15:45:04.490507400 UTC
        File attribute flags            : 0x00000020
                Should be archived (FILE_ATTRIBUTE_ARCHIVE)
        Name space                      : DOS (2)
        Name                            : WI506F~1.VMD

Attribute: 4
        Type                            : $FILE_NAME (0x00000030)
        Parent file reference           : 707654-48
        Creation time                   : Sep 07, 2020 15:45:04.490507400 UTC
        Modification time               : Sep 07, 2020 15:45:04.490507400 UTC
        Access time                     : Sep 07, 2020 15:45:04.490507400 UTC
        Entry modification time         : Sep 07, 2020 15:45:04.490507400 UTC
        File attribute flags            : 0x00000020
                Should be archived (FILE_ATTRIBUTE_ARCHIVE)
        Name space                      : Windows (1)
        Name                            : Windows Server 2016-000009.vmdk

Attribute: 5
        Type                            : $DATA (0x00000080)
        Data VCN range                  : 248301 - 417095
        Data flags                      : 0x0000

Attribute: 6
        Type                            : $DATA (0x00000080)
        Data VCN range                  : 0 - 248300
        Data size                       : 2667970560 bytes
        Data flags                      : 0x0000

Attribute: 7
        Type                            : $DATA (0x00000080)
        Data VCN range                  : 417096 - 651359
        Data flags                      : 0x0000

`

**Comment by joachimmetz** [comment] 2020-10-28 10:46
> After the changes, it worked like a charm :)

Ack, good to hear, thx for confirming. I'll close the issue.

**Closed by joachimmetz** 2020-10-28 10:46 UTC
Labels: enhancement
